# Generated by Django 5.1.3 on 2024-11-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
