# Generated by Django 5.1.3 on 2024-12-01 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_lost_or_found',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
